[window]
opacity = 0.7

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]
normal.family = "JetBrainsMono"
bold.family = "JetBrainsMono"
italic.family = "JetBrainsMono"
bold_italic.family = "JetBrainsMono"
size = 10.0

[colors]
primary.foreground = "#fff4d2"
primary.background = "#000000"
